name: 👤 New Contributor
description: First-time contributor? Start here ✨
title: Add Contributor
labels: ["item:contributor"]
body:
- type: input
  id: name
  attributes:
    label: Name
    description: Name as you would like it displayed on your photos
  validations:
    required: true
- type: input
  id: year
  attributes:
    label: URL
    description: (Optional) Link to your website or social media profile
    placeholder: ex., “https://example.com”
