name: New Photo
description: Submit a new photo to be published on Written in Stone
title: Add “[Name] ([Year])”
labels: ["item:photo"]
body:
- type: input
  id: name
  attributes:
    label: Name
    description: Name of person or company shown on the stamp or seal.
    placeholder: ex., “City Sidewalk Co.”
  validations:
    required: true
- type: input
  id: year
  attributes:
    label: Year
    description: Year shown on the stamp or seal. (Optional)
    placeholder: ex., “1982”
- type: textarea
  id: photo
  attributes:
    label: Photo
  validations:
    required: true
- type: input
  id: photoDate
  attributes:
    label: "Photo: Date"
    description: Date the photo was taken
    placeholder: ex., “2023-12-31”
- type: input
  id: neighborhood
  attributes:
    label: "Location: Neighborhood"
    description: Name of the neighborhood where the seal or stamp is located. (Optional)
- type: input
  id: city
  attributes:
    label: "Location: City"
    description: Name of the city where the seal or stamp is located.
  validations:
    required: true
- type: input
  id: state
  attributes:
    label: "Location: State/Province"
    description: Name of the state or province where the seal or stamp is located.
  validations:
    required: true
